"""Sprint 1 - modeles initiaux

Revision ID: 7fc5b6e27875
Revises: 
Create Date: 2026-06-03 13:15:20.528120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fc5b6e27875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=False, comment='bcrypt hash du secret client'),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('redirect_uris', postgresql.ARRAY(sa.Text()), nullable=False, comment='URIs de redirection autorisées (exact match obligatoire)'),
    sa.Column('allowed_scopes', postgresql.ARRAY(sa.Text()), server_default=sa.text("ARRAY['openid','profile','email']::text[]"), nullable=False),
    sa.Column('grant_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logo_uri', sa.Text(), nullable=True, comment='URL du logo (page de consentement)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth2_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth2_clients_client_id'), ['client_id'], unique=True)

    op.create_table('rs256_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kid', sa.String(length=64), nullable=False, comment='Key ID inclus dans le header JWT et exposé dans /jwks.json'),
    sa.Column('private_key_encrypted', sa.Text(), nullable=False, comment='Clé privée RSA 2048 bits chiffrée AES-256-GCM'),
    sa.Column('public_key_pem', sa.Text(), nullable=False, comment='Clé publique RSA (format PEM) — exposée via /jwks.json'),
    sa.Column('algorithm', sa.String(length=16), server_default=sa.text("'RS256'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True = utilisée pour signer. False = conservée pour vérifier.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='created_at + 90 jours'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rs256_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rs256_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rs256_keys_kid'), ['kid'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=512), nullable=True, comment='Clé TOTP chiffrée AES-256-GCM'),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', postgresql.ARRAY(sa.Text()), nullable=True, comment='Codes de secours hachés bcrypt'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Verrouillage temporaire (10 échecs consécutifs)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment="Type d'événement (login_success, token_revoked, ...)"),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False, comment="Adresse IP de l'action"),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Métadonnées JSONB (sans données sensibles)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_created_event', ['created_at', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_audit_logs_user_event', ['user_id', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('oauth2_authorization_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=True),
    sa.Column('code_challenge', sa.String(length=128), nullable=True, comment='BASE64URL(SHA256(code_verifier))'),
    sa.Column('code_challenge_method', sa.String(length=16), nullable=True, comment='Toujours S256 — plain est refusé'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth2_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth2_authorization_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth2_authorization_codes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth2_authorization_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth2_authorization_codes_user_id'), ['user_id'], unique=False)

    op.create_table('oauth2_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False, comment='JWT ID (identifiant unique du token, pour blacklist Redis)'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False, comment='bcrypt hash du refresh token'),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('access_token_jti', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth2_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth2_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth2_tokens_access_token_jti'), ['access_token_jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth2_tokens_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth2_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_oauth2_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth2_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth2_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_oauth2_tokens_client_id'))
        batch_op.drop_index(batch_op.f('ix_oauth2_tokens_access_token_jti'))

    op.drop_table('oauth2_tokens')
    with op.batch_alter_table('oauth2_authorization_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_authorization_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth2_authorization_codes_code'))
        batch_op.drop_index(batch_op.f('ix_oauth2_authorization_codes_client_id'))

    op.drop_table('oauth2_authorization_codes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_user_event')
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index('ix_audit_logs_created_event')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_client_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rs256_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rs256_keys_kid'))
        batch_op.drop_index(batch_op.f('ix_rs256_keys_is_active'))

    op.drop_table('rs256_keys')
    with op.batch_alter_table('oauth2_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth2_clients_client_id'))

    op.drop_table('oauth2_clients')
    # ### end Alembic commands ###
